### ISSUE TITLE
end-to-end model?

### ISSUE THREAD

**Issue by Alexanderisgod** [Robertwyq/LSMOL#1]
Hi, I read your paper. I find that the algorithm seems train two models (3D and 2D) seperately, empolying EM thinking. Is it impossible to aggreate the two model? and if you use the memory bank to store the previous pseudo label?  Truely, it's need careful design and traning method. Thank for u work.

**Comment by Robertwyq** [comment]
Yeah, we train two models separately. We believe it is possible to aggregate the two model (inspired by current BEV methods), but the training would be difficult. The core of this work is the optimization of pseudo label in two modalities. The pseudo label saved in offline manner. 
Maybe in the future, we would like to try an end-to-end method, this work is only an initial attempt, utilizing the natural geometric information to train the model instead of human supervision.
